 [features]
seeds = false
skip-lint = false
idl-build = ["anchor-spl/idl-build"]

[programs.localnet]
sol_savings = "AL2pejr3LLKAiE47G64Br3XprkyrmymLzMQiqZMhQVoa"

[programs.devnet]
sol_savings = "AL2pejr3LLKAiE47G64Br3XprkyrmymLzMQiqZMhQVoa"

[programs.mainnet]
sol_savings = "AL2pejr3LLKAiE47G64Br3XprkyrmymLzMQiqZMhQVoa"

[registry]
url = "https://anchor.projectserum.com" # Default Anchor registry

[provider]
cluster = "localnet"
wallet = "~/Users/ahmadkhan/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p tsconfig.json tests/**/*.ts"

[test]
startup_wait = 5000

[workspace]
types = "target/types/sol_savings"