[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_savings = "HamacCCe7hLEBqMKcRebMCTdATkQSUtRpE2xkHc236gZ"

[programs.devnet]
sol_savings = "HamacCCe7hLEBqMKcRebMCTdATkQSUtRpE2xkHc236gZ"

[programs.mainnet]
sol_savings = "HamacCCe7hLEBqMKcRebMCTdATkQSUtRpE2xkHc236gZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"

[workspace]
types = "target/types/sol_savings"