[features]
seeds = false
skip-lint = false
idl-build = ["anchor-spl/idl-build"]

[programs.localnet]
sol_savings = "HamacCCe7hLEBqMKcRebMCTdATkQSUtRpE2xkHc236gZ"

[programs.devnet]
sol_savings = "HamacCCe7hLEBqMKcRebMCTdATkQSUtRpE2xkHc236gZ"

[programs.mainnet]
sol_savings = "HamacCCe7hLEBqMKcRebMCTdATkQSUtRpE2xkHc236gZ"

[registry]
url = "https://anchor.projectserum.com" # Default Anchor registry

[provider]
cluster = "devnet"
wallet = "~/Users/ahmadkhan/Users/ahmadkhan/Users/ahmadkhan/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p tsconfig.json tests/**/*.ts"

[test]
startup_wait = 5000

[workspace]
types = "target/types/sol_savings"
