[programs.localnet]
deposit_withdraw = "27EvSTnpN61RPkypusJM3yk2a9qA1utPsgNfpwhpYFBw"
[programs.devnet]
deposit_withdraw = "27EvSTnpN61RPkypusJM3yk2a9qA1utPsgNfpwhpYFBw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.18.2"